version: "3.8"

services:
  app:
    build: .
    container_name: app
    environment:
      - DATABASE_URL=mysql://dbuser:dbpassword@db/dub_sh
      - UPSTASH_REDIS_REST_URL=redis://redis:6379/1
      - UPSTASH_REDIS_REST_TOKEN=x
    ports:
      - 3000:3000
    networks:
      - dub
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=dub_sh
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql" ,"-h", "db", "-P", "3306", "-u", "root", "-prootpassword", "-e", "SELECT VERSION()"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - dub
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  redis:
    image: redis:6.0
    container_name: redis
    networks:
      - dub
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  dub:
    name: dub

volumes:
  db_data:
